const PDFDocument = require('pdfkit');

// ── Design tokens ────────────────────────────────────────────────────────────
const C = {
  headerBg: '#100b2e',
  purple:   '#7c3aed',
  teal:     '#10b981',
  amber:    '#d97706',
  text:     '#111827',
  mid:      '#374151',
  muted:    '#6b7280',
  divider:  '#e5e7eb',
  lilac:    '#c4b5fd',
  white:    '#ffffff',
};

// ── Helpers ───────────────────────────────────────────────────────────────────
function fmtDate(d) {
  if (!d) return '';
  const dt = new Date(typeof d === 'number' ? d : d);
  if (isNaN(dt.getTime())) return '';
  return dt.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
}

function fmtDur(dur) {
  if (!dur) return '';
  const m = String(dur.audioMinutes || 0).padStart(2, '0');
  const s = String(dur.audioSeconds || 0).padStart(2, '0');
  return `${m}m ${s}s`;
}

// ── Core builder ──────────────────────────────────────────────────────────────
function buildPdf(label, title, date, duration, drawBody) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 0, bottom: 0, left: 0, right: 0 },
        bufferPages: true,
        info: { Title: title || label, Creator: 'Recora' },
      });

      const chunks = [];
      doc.on('data',  c  => chunks.push(c));
      doc.on('end',   () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const W = doc.page.width;    // 595.28 (A4)
      const H = doc.page.height;   // 841.89
      const M = 50;                // content left/right margin

      // ── Header ─────────────────────────────────────────────────────────────
      doc.rect(0, 0, W, 76).fill(C.headerBg);
      doc.rect(0, 0, 5, 76).fill(C.purple);
      doc.fillColor(C.white).font('Helvetica-Bold').fontSize(18).text('RECORA', M, 22);
      doc.fillColor(C.lilac).font('Helvetica').fontSize(9.5).text(label, M, 47);

      // Type badge
      const badgeW = 130;
      doc.roundedRect(W - badgeW - 20, 25, badgeW, 22, 4).fill(C.purple);
      doc.fillColor(C.white).font('Helvetica-Bold').fontSize(8.5)
        .text(label.toUpperCase(), W - badgeW - 20, 33, { width: badgeW, align: 'center' });

      // ── Title + meta ───────────────────────────────────────────────────────
      doc.y = 100;

      doc.fillColor(C.text).font('Helvetica-Bold').fontSize(17)
        .text(title || 'Untitled Meeting', M, doc.y, { width: W - M * 2 });
      doc.moveDown(0.45);

      const parts = [];
      const dateStr = fmtDate(date);
      const durStr  = fmtDur(duration);
      if (dateStr) parts.push(dateStr);
      if (durStr)  parts.push(`Duration: ${durStr}`);
      if (parts.length) {
        doc.fillColor(C.muted).font('Helvetica').fontSize(9)
          .text(parts.join('   |   '), M, doc.y);
        doc.moveDown(0.8);
      }

      doc.rect(M, doc.y, W - M * 2, 0.75).fill(C.divider);
      doc.y += 16;

      // ── Body ──────────────────────────────────────────────────────────────
      drawBody(doc, W, M, H);

      // ── Footer on all pages ───────────────────────────────────────────────
      const today  = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
      const range  = doc.bufferedPageRange();
      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(range.start + i);
        const fy = H - 34;
        doc.rect(0, fy - 0.5, W, 0.5).fill(C.divider);
        doc.fillColor(C.muted).font('Helvetica').fontSize(7.5)
          .text(
            `Generated by Recora  |  ${today}  |  Page ${i + 1} of ${range.count}`,
            M, fy + 7, { width: W - M * 2, align: 'center' }
          );
      }

      doc.flushPages();
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// ── Section block ─────────────────────────────────────────────────────────────
function drawSection(doc, W, M, heading, items, accentColor) {
  if (!items || items.length === 0) return;

  const headY = doc.y;
  doc.rect(M, headY, 3.5, 14).fill(accentColor);
  doc.fillColor(C.text).font('Helvetica-Bold').fontSize(11.5)
    .text(heading, M + 12, headY + 1, { width: W - M * 2 - 12 });
  doc.moveDown(0.5);

  items.forEach(item => {
    const text = String(item || '').trim();
    if (!text) return;
    const iy = doc.y;
    doc.fillColor(accentColor).font('Helvetica-Bold').fontSize(9)
      .text('–', M + 14, iy);
    doc.fillColor(C.mid).font('Helvetica').fontSize(9.5)
      .text(text, M + 28, iy, { width: W - M * 2 - 28, lineGap: 2.5 });
    doc.moveDown(0.1);
  });

  doc.moveDown(0.55);
}

// ── Transcript section ────────────────────────────────────────────────────────
function drawTranscript(doc, W, M, transcript, withDivider) {
  if (!transcript || transcript.length === 0) return;

  if (withDivider) {
    doc.moveDown(0.2);
    doc.rect(M, doc.y, W - M * 2, 0.75).fill(C.divider);
    doc.y += 14;
  }

  const headY = doc.y;
  doc.rect(M, headY, 3.5, 14).fill(C.muted);
  doc.fillColor(C.text).font('Helvetica-Bold').fontSize(11.5)
    .text('Transcript', M + 12, headY + 1, { width: W - M * 2 });
  doc.moveDown(0.6);

  transcript.forEach(u => {
    const uy = doc.y;
    doc.fillColor(C.purple).font('Helvetica-Bold').fontSize(8.5)
      .text(`${u.speaker}`, M + 12, uy, { continued: false });
    doc.fillColor(C.muted).font('Helvetica').fontSize(7.5)
      .text(`${u.timestamp}`, M + 12, uy, { align: 'right', width: W - M * 2 - 12 });
    doc.fillColor(C.mid).font('Helvetica').fontSize(9.5)
      .text(u.text || '', M + 20, doc.y, { width: W - M * 2 - 20, lineGap: 2.5 });
    doc.moveDown(0.4);
  });
}

// ── Public generators ─────────────────────────────────────────────────────────
function generateMomPdf(rec, calEvent) {
  const attendees = (calEvent?.attendees || [])
    .map(a => a.displayName || a.email)
    .filter(Boolean);

  return buildPdf('Minutes of Meeting', rec.title, rec.createdAt, rec.duration, (doc, W, M) => {
    if (attendees.length) drawSection(doc, W, M, 'Attendees',    attendees,                      C.purple);

    const s = rec.summary || {};
    drawSection(doc, W, M, 'Key Points',   s.key_points   || [], C.purple);
    drawSection(doc, W, M, 'Decisions',    s.decisions    || [], C.amber);
    drawSection(doc, W, M, 'Action Items', s.action_items || [], C.teal);

    drawTranscript(doc, W, M, rec.transcript, true);
  });
}

function generateSummaryPdf(rec) {
  return buildPdf('Meeting Summary', rec.title, rec.createdAt, rec.duration, (doc, W, M) => {
    const s = rec.summary || {};
    drawSection(doc, W, M, 'Key Points',   s.key_points   || [], C.purple);
    drawSection(doc, W, M, 'Decisions',    s.decisions    || [], C.amber);
    drawSection(doc, W, M, 'Action Items', s.action_items || [], C.teal);
  });
}

function generateTranscriptPdf(rec) {
  return buildPdf('Meeting Transcript', rec.title, rec.createdAt, rec.duration, (doc, W, M) => {
    if (!(rec.transcript || []).length) {
      doc.fillColor(C.muted).font('Helvetica').fontSize(10).text('No transcript available.', M);
      return;
    }
    drawTranscript(doc, W, M, rec.transcript, false);
  });
}

module.exports = { generateMomPdf, generateSummaryPdf, generateTranscriptPdf };
